# Generated by Django 4.2.7 on 2024-05-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonluz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Margen de ganancia'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.BooleanField(blank=True, null=True, verbose_name='Publicado en MercadoLibre'),
        ),
    ]
