# Generated by Django 4.2.7 on 2024-05-09 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=100, unique=True, verbose_name='Codigo')),
                ('article_name', models.CharField(max_length=150, verbose_name='Articulo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(default='null', upload_to='articles', verbose_name='Imagen')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Costo')),
                ('tax_iva', models.DecimalField(blank=True, choices=[(10.5, '10,5'), (21, '21')], decimal_places=2, max_digits=4, null=True, verbose_name='Tipo de iva')),
                ('margin', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Margen de ganancia')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de venta')),
                ('public', models.BooleanField(verbose_name='Publicado en ML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('article_type', models.BooleanField(choices=[(False, 'Producto fabricado'), (True, 'Adquirido terminado')], verbose_name='Reventa')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la pieza')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(default='null', upload_to='parts', verbose_name='Imagen')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Costo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='ArticleParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad necesaria')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonluz.article', verbose_name='Articulo')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonluz.parts', verbose_name='Pieza')),
            ],
            options={
                'verbose_name': 'Pieza del articulo',
                'verbose_name_plural': 'Piezas de los articulos',
                'ordering': ['-quantity'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='fonluz.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='article',
            name='modify_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='article',
            name='necessary_parts',
            field=models.ManyToManyField(through='fonluz.ArticleParts', to='fonluz.parts', verbose_name='Partes necesarias'),
        ),
    ]
