# Generated by Django 4.2.7 on 2024-05-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonluz', '0002_alter_article_cost_alter_article_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.BooleanField(choices=[(False, 'Fabricacion propia'), (True, 'Adquirido terminado')], default=False, verbose_name='Tipo de producto'),
        ),
    ]
