# Generated by Django 4.2.7 on 2024-05-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True, verbose_name='Total a pagar'),
        ),
    ]
