# Generated by Django 4.2.7 on 2024-05-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=11, unique=True, verbose_name='DNI/CUIT/CUIL')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=155, verbose_name='E-Mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
